url = "https://www.brainyquote.com/search_results?x=0&y=0&q="
url_quote_topics = "https://www.brainyquote.com/topics/"

quote_topics = [
    ['Age',
    'Alone',
    'Amazing',
    'Anger',
    'Anniversary',
    'Architecture',
    'Art Favorite',
    'Attitude',
    'Beauty',
    'Best',
    'Birthday'],
    ['Brainy',
    'Business',
    'Car',
    'Chance',
    'Change',
    'Christmas',
    'Communication',
    'Computers',
    'Cool',
    'Courage',
    'Dad'],
    ['Dating',
    'Death',
    'Design',
    'Diet',
    'Dreams',
    'Easter',
    'Education',
    'Environmental',
    'Equality',
    'Experience',
    'Failure'],
    ['Faith',
    'Family',
    'Famous',
    'Father s Day',
    'Fear',
    'Finance',
    'Fitness',
    'Food',
    'Forgiveness',
    'Freedom',
    'Friendship Favorite'],
    ['Funny',
    'Future',
    'Gardening',
    'God',
    'Good',
    'Government',
    'Graduation',
    'Great',
    'Happiness',
    'Health',
    'History'],
    ['Home',
    'Hope',
    'Humor',
    'Imagination',
    'Independence',
    'Inspirational',
    'Intelligence',
    'Jealousy',
    'Knowledge',
    'Leadership',
    'Learning'],
    ['Legal',
    'Life Favorite',
    'Love Favorite',
    'Marriage',
    'Medical',
    'Memorial Day',
    'Men',
    'Mom',
    'Money',
    'Morning',
    'Mother s Day'],
    ['Motivational Favorite',
    'Movies',
    'Moving On',
    'Music',
    'Nature',
    'New Year s',
    'Parenting',
    'Patience',
    'Patriotism',
    'Peace',
    'Pet'],
    ['Poetry',
    'Politics',
    'Positive',
    'Power',
    'Relationship',
    'Religion',
    'Respect',
    'Romantic',
    'Sad',
    'Saint Patrick s Day',
    'Science'],
    ['Smile',
    'Society',
    'Space',
    'Sports',
    'Strength',
    'Success Favorite',
    'Sympathy',
    'Teacher',
    'Technology',
    'Teen',
    'Thankful'],
    ['Thanksgiving',
    'Time',
    'Travel',
    'Trust',
    'Truth',
    'Veterans Day',
    'War',
    'Wedding',
    'Wisdom Favorite',
    'Women',
    'Work'],
]